<?php

// autoload-files.php @generated by Strauss
// @see https://github.com/BrianHenryIE/strauss/

require_once __DIR__ . '/symfony/deprecation-contracts/function.php';
require_once __DIR__ . '/symfony/polyfill-ctype/bootstrap.php';
